export const TAX_CATEGORIES = {
  // Income
  INCOME_AIRDROP: 'INCOME_AIRDROP',
  INCOME_STAKING_REWARD: 'INCOME_STAKING_REWARD',
  INCOME_MINING: 'INCOME_MINING',
  INCOME_SALARY: 'INCOME_SALARY',
  INCOME_OTHER: 'INCOME_OTHER',

  // Disposal
  DISPOSAL_SALE: 'DISPOSAL_SALE',
  DISPOSAL_SWAP: 'DISPOSAL_SWAP',
  DISPOSAL_GIFT_OUT: 'DISPOSAL_GIFT_OUT',

  // Non-taxable transfers
  TRANSFER_INTERNAL: 'TRANSFER_INTERNAL',
  TRANSFER_TO_EXCHANGE: 'TRANSFER_TO_EXCHANGE',
  TRANSFER_FROM_EXCHANGE: 'TRANSFER_FROM_EXCHANGE',
  GIFT_RECEIVED: 'GIFT_RECEIVED',

  // DeFi
  DEFI_LP_ADD: 'DEFI_LP_ADD',
  DEFI_LP_REMOVE: 'DEFI_LP_REMOVE',
  DEFI_BORROW: 'DEFI_BORROW',
  DEFI_REPAY: 'DEFI_REPAY',

  // Bridge
  BRIDGE_OUT: 'BRIDGE_OUT',
  BRIDGE_IN: 'BRIDGE_IN',

  // Special
  DUST: 'DUST',
  TOKEN_MIGRATION: 'TOKEN_MIGRATION',
  FEE: 'FEE',
  SPAM: 'SPAM',
  PENDING_REVIEW: 'PENDING_REVIEW',
} as const;

export type TaxCategory = typeof TAX_CATEGORIES[keyof typeof TAX_CATEGORIES];

export const FISCAL_IMPACT = {
  INCOME: 'INCOME',
  DISPOSAL: 'DISPOSAL',
  NON_TAXABLE: 'NON_TAXABLE',
  DEFERRED: 'DEFERRED',
  PENDING: 'PENDING',
} as const;

export type FiscalImpact = typeof FISCAL_IMPACT[keyof typeof FISCAL_IMPACT];

export const TAX_CATEGORY_FISCAL_MAP: Record<TaxCategory, FiscalImpact> = {
  // Income
  INCOME_AIRDROP: FISCAL_IMPACT.INCOME,
  INCOME_STAKING_REWARD: FISCAL_IMPACT.INCOME,
  INCOME_MINING: FISCAL_IMPACT.INCOME,
  INCOME_SALARY: FISCAL_IMPACT.INCOME,
  INCOME_OTHER: FISCAL_IMPACT.INCOME,

  // Disposal
  DISPOSAL_SALE: FISCAL_IMPACT.DISPOSAL,
  DISPOSAL_SWAP: FISCAL_IMPACT.DISPOSAL,
  DISPOSAL_GIFT_OUT: FISCAL_IMPACT.DISPOSAL,

  // Non-taxable
  TRANSFER_INTERNAL: FISCAL_IMPACT.NON_TAXABLE,
  TRANSFER_TO_EXCHANGE: FISCAL_IMPACT.NON_TAXABLE,
  TRANSFER_FROM_EXCHANGE: FISCAL_IMPACT.NON_TAXABLE,
  GIFT_RECEIVED: FISCAL_IMPACT.NON_TAXABLE,

  // DeFi — deferred
  DEFI_LP_ADD: FISCAL_IMPACT.DEFERRED,
  DEFI_LP_REMOVE: FISCAL_IMPACT.DEFERRED,
  DEFI_BORROW: FISCAL_IMPACT.NON_TAXABLE,
  DEFI_REPAY: FISCAL_IMPACT.NON_TAXABLE,

  // Bridge — deferred
  BRIDGE_OUT: FISCAL_IMPACT.DEFERRED,
  BRIDGE_IN: FISCAL_IMPACT.DEFERRED,

  // Special
  DUST: FISCAL_IMPACT.NON_TAXABLE,
  TOKEN_MIGRATION: FISCAL_IMPACT.NON_TAXABLE,
  FEE: FISCAL_IMPACT.DISPOSAL,
  SPAM: FISCAL_IMPACT.NON_TAXABLE,
  PENDING_REVIEW: FISCAL_IMPACT.PENDING,
};

export function getFiscalImpact(category: TaxCategory): FiscalImpact {
  return TAX_CATEGORY_FISCAL_MAP[category];
}

export function getAllTaxCategories(): Array<{ category: TaxCategory; fiscalImpact: FiscalImpact }> {
  return Object.entries(TAX_CATEGORY_FISCAL_MAP).map(([category, fiscalImpact]) => ({
    category: category as TaxCategory,
    fiscalImpact,
  }));
}
